# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'CanZE4iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CanZE4iOS

  pod 'Toast-Swift', '~> 5.0.1'

end
