# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'CanZE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CanZE4iOS

  pod 'Charts'
  pod 'Firebase'
  pod 'Toast-Swift', '~> 5.0.1'

end
